"""added the user class password hash and bcrpt functions

Revision ID: 831345019c62
Revises: 3f1bb5ad9bcc
Create Date: 2023-10-25 09:48:04.643442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831345019c62'
down_revision = '3f1bb5ad9bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
